name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: android-actions/setup-android@v2
        with:
          sdk: |
            platform-tools
            build-tools:33.0.2
            platforms;android-33

      - run: ./gradlew assembleDebug

      - uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
